import { _electron as electron } from 'playwright';
import { Mp3Encoder } from '@breezystack/lamejs';
import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';

const output = path.resolve('test-output'), data = path.join(output, `library-${Date.now()}`), source = path.join(data, 'source');
await fs.mkdir(path.join(source, 'ignored-subfolder'), { recursive: true });
function mp3(seconds, hz) {
  const rate = 44100, samples = new Int16Array(rate * seconds);
  for (let i = 0; i < samples.length; i++) samples[i] = Math.sin(i * 2 * Math.PI * hz / rate) * 10000;
  const encoder = new Mp3Encoder(1, rate, 128), chunks = [];
  for (let i = 0; i < samples.length; i += 1152) chunks.push(Buffer.from(encoder.encodeBuffer(samples.subarray(i, i + 1152))));
  chunks.push(Buffer.from(encoder.flush())); return Buffer.concat(chunks);
}
await fs.writeFile(path.join(source, '01 · Midnight Drive.mp3'), mp3(8, 440));
await fs.writeFile(path.join(source, '02 · Afterglow.mp3'), mp3(5, 330));
await fs.writeFile(path.join(source, 'notes.txt'), 'Nicht importieren');
await fs.writeFile(path.join(source, 'ignored-subfolder', 'nested.mp3'), mp3(1, 220));
let desktop, latestPage;
async function launch() {
  const env = { ...process.env, GIGMAN_DATA_DIR: data };
  delete env.ELECTRON_RUN_AS_NODE;
  desktop = await electron.launch({ args: ['.'], env, ...(process.env.GIGMAN_EXECUTABLE ? { executablePath: process.env.GIGMAN_EXECUTABLE } : {}) });
  const page = await desktop.firstWindow(); latestPage = page;
  await page.waitForSelector('.brand'); return page;
}
const errors = [];
try {
  let page = await launch();
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') console.log('Renderer:', message.text()); });
  await desktop.evaluate(({ dialog }, source) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [source] }); }, source);
  await page.locator('[data-action="new"]').first().click();
  await page.locator('[name="name"]').fill('Club Sessions');
  await page.locator('dialog button[type="submit"]').click();
  await page.waitForFunction(() => document.querySelectorAll('.song-row').length === 2 && !document.body.textContent.includes('Waveform wird geladen'));
  assert.equal(await page.locator('.song-row').count(), 2, 'Nur MP3s ohne Unterverzeichnisse');
  const songId = await page.locator('.song-row').first().getAttribute('data-song');
  assert.equal(await page.locator('.heading').count(), 0, 'Großer Kopfbereich wurde entfernt');
  assert.equal(await page.locator('.topbar [data-action="rename"]').count(), 1);
  assert.equal(await page.locator('.topbar [data-action="youtube"]').count(), 1);
  assert.equal(await page.locator('.topbar [data-action="import-folder"]').count(), 1);
  assert.equal(Math.round((await page.locator('.song-row').first().boundingBox()).height), 140, 'Songzeile ist 20% kleiner');
  await page.locator('[data-action="select-song"]').first().dblclick();
  await page.locator('.song-name-editor').fill('Midnight Drive · Übung');
  await page.locator('.song-name-editor').press('Enter');
  assert.equal(await page.locator('[data-action="select-song"]').first().textContent(), 'Midnight Drive · Übung');
  await page.locator('[data-action="select-song"]').first().dblclick();
  await page.locator('.song-name-editor').fill('Nicht übernehmen');
  await page.locator('.song-name-editor').press('Escape');
  assert.equal(await page.locator('[data-action="select-song"]').first().textContent(), 'Midnight Drive · Übung');
  await page.locator('[data-action="select-song"]').first().dblclick();
  await page.locator('.song-name-editor').fill('Midnight Drive · Live');
  await page.locator('.topbar h1').click();
  assert.equal(await page.locator('[data-action="select-song"]').first().textContent(), 'Midnight Drive · Live');
  const copied = await fs.readdir(path.join(data, 'audio'));
  assert.equal(copied.length, 2);
  assert.ok((await fs.stat(path.join(data, 'audio', copied[0]))).size > 10000);
  const wave = page.locator('.song-row').first().locator('.wave');
  const rect = await wave.boundingBox();
  await page.mouse.move(rect.x + rect.width * 0.1, rect.y + 55);
  await page.mouse.down(); await page.mouse.move(rect.x + rect.width * 0.3, rect.y + 55, { steps: 12 }); await page.mouse.up();
  await page.locator('[name="name"]').fill('Solo 1');
  await page.locator('[name="start"]').fill('0.2'); await page.locator('[name="end"]').fill('0.6');
  await page.locator('dialog button[type="submit"]').click();
  await page.locator('.song-row').first().locator('[data-action="new-section"]').click();
  await page.locator('[name="name"]').fill('Solo 2');
  await page.locator('[name="start"]').fill('1.0'); await page.locator('[name="end"]').fill('1.4');
  await page.locator('dialog button[type="submit"]').click();
  assert.equal(await page.locator('.region').count(), 2);
  await page.locator('.gap-input').first().fill('1'); await page.locator('.gap-input').first().dispatchEvent('change');
  await page.locator('#count').selectOption('0');
  await page.evaluate(() => {
    window.audioStarts = [];
    const original = AudioBufferSourceNode.prototype.start;
    AudioBufferSourceNode.prototype.start = function (when, offset, duration) {
      window.audioStarts.push({ when, offset, duration, loop: this.loop, loopStart: this.loopStart, loopEnd: this.loopEnd, tempo: this.playbackRate.value });
      return original.call(this, when, offset, duration);
    };
    const connect = AudioNode.prototype.connect;
    AudioNode.prototype.connect = function (...args) {
      if (this instanceof AudioWorkletNode) window.soundtouch = this;
      return connect.apply(this, args);
    };
  });
  await page.locator('[data-action="mode-loop"]').click();
  await page.locator('[data-action="preview"]').first().click();
  await page.waitForFunction(() => window.audioStarts.length === 1);
  let previewStart = await page.evaluate(() => window.audioStarts.at(-1));
  assert.equal(previewStart.loop, false, 'Vollständige Vorschau funktioniert auch im Loop Mode');
  assert.ok(previewStart.duration > 8, 'Vorschau überspringt keine unmarkierten Songteile');
  let previewWave = await page.locator('.wave').first().boundingBox();
  await page.mouse.click(previewWave.x + previewWave.width * 0.65, previewWave.y + 65);
  await page.waitForFunction(() => window.audioStarts.length === 2);
  previewStart = await page.evaluate(() => window.audioStarts.at(-1));
  assert.ok(previewStart.offset > 5 && !previewStart.loop, 'Waveform-Klick sucht eine Stelle ohne Loop');
  await page.keyboard.press('Space'); await page.keyboard.press('Space');
  await page.waitForFunction(() => window.audioStarts.length === 3);
  assert.equal((await page.evaluate(() => window.audioStarts.at(-1))).loop, false, 'Vorschau bleibt nach Pause ohne Loop');
  await page.keyboard.press('Escape'); await page.locator('[data-action="mode-song"]').click();
  await page.evaluate(() => { window.audioStarts = []; });
  await page.locator('[data-action="play"]').click();
  await page.waitForFunction(() => window.audioStarts.length === 2);
  await page.waitForFunction(() => document.querySelector('#play-status').textContent.includes('Gitarrenwechsel'));
  await page.waitForFunction(() => window.audioStarts.length === 3);
  let starts = await page.evaluate(() => window.audioStarts);
  assert.deepEqual(starts.map(s => s.offset), [0.2, 1, 0]);
  assert.ok(starts[2].when - starts[1].when > 1.3, 'Wechselpause zwischen Songs');
  await page.keyboard.press('Escape');
  await page.locator('.region').first().click(); await page.locator('[data-action="mode-loop"]').click();
  await page.locator('#tempo').fill('0.75'); await page.locator('#tempo').dispatchEvent('change');
  await page.locator('[data-action="pitch-down"]').click();
  await page.locator('[data-action="play"]').click();
  await page.waitForFunction(() => window.audioStarts.at(-1).loop);
  starts = await page.evaluate(() => window.audioStarts);
  assert.equal(starts.at(-1).tempo, 0.75);
  assert.equal(starts.at(-1).loopStart, 0.2); assert.equal(starts.at(-1).loopEnd, 0.6);
  assert.equal(await page.evaluate(() => window.soundtouch.parameters.get('pitchSemitones').value), -1);
  await page.evaluate(() => {
    window.probe = window.soundtouch.context.createAnalyser(); window.probe.fftSize = 8192;
    window.soundtouch.connect(window.probe);
    const silent = window.soundtouch.context.createGain(); silent.gain.value = 0;
    window.probe.connect(silent); silent.connect(window.soundtouch.context.destination);
  });
  await page.waitForTimeout(1000);
  const frequency = await page.evaluate(() => {
    const data = new Float32Array(window.probe.frequencyBinCount); window.probe.getFloatFrequencyData(data);
    let max = 0; for (let i = 1; i < data.length; i++) if (data[i] > data[max]) max = i;
    return max * window.probe.context.sampleRate / window.probe.fftSize;
  });
  assert.ok(Math.abs(frequency - 440 * 2 ** (-1 / 12)) < 20, `Tonhöhe bleibt bei 75% Tempo korrekt: ${frequency.toFixed(1)} Hz`);
  assert.ok((await page.locator('#play-status').textContent()).includes('Loop'));
  await page.keyboard.press('Space'); await page.keyboard.press('Space');
  await page.waitForFunction(() => window.audioStarts.length >= 5);
  assert.equal((await page.evaluate(() => window.audioStarts)).at(-1).loopStart, 0.2, 'Pause erhält die vollständigen Loop-Grenzen');
  await page.keyboard.press('Escape');
  await page.locator('[data-action="mode-song"]').click();
  await page.locator('#count').selectOption('4');
  await page.locator('[data-action="play"]').click();
  await page.waitForFunction(() => document.querySelector('#play-status').textContent.includes('Vorzählen'));
  await page.keyboard.press('Escape');
  await page.locator('.region').first().dblclick();
  await page.locator('[name="end"]').fill('1000'); await page.locator('dialog button[type="submit"]').click();
  assert.ok(await page.locator('.form-error').textContent());
  await page.locator('[name="end"]').fill('0.8'); await page.locator('dialog button[type="submit"]').click();
  await page.locator('.drag-handle').first().dragTo(page.locator('.song-row').last());
  assert.notEqual(await page.locator('.song-row').first().getAttribute('data-song'), songId);
  await page.locator('[data-action="rename"]').click(); await page.locator('[name="name"]').fill('Friday Night · Live'); await page.locator('dialog button[type="submit"]').click();
  await page.screenshot({ path: path.join(output, 'gigman.png'), fullPage: true });
  await page.waitForTimeout(600);
  assert.deepEqual(errors, []);
  const saved = JSON.parse(await fs.readFile(path.join(data, 'library.json'), 'utf8'));
  assert.equal(saved.setlists[0].name, 'Friday Night · Live');
  assert.equal(saved.setlists[0].songs[1].sections[0].end, 0.8);
  await desktop.close(); desktop = null;
  page = await launch();
  await page.waitForFunction(() => document.querySelectorAll('.region').length === 2);
  assert.equal(await page.locator('h1').textContent(), 'Friday Night · Live');
  assert.equal(await page.locator('#tempo').inputValue(), '0.75');
  assert.equal(await page.locator('.gap-input').last().inputValue(), '1');
  assert.equal(await page.locator('[data-action="select-song"]').last().textContent(), 'Midnight Drive · Live', 'Songname wird nach Neustart wiederhergestellt');
  const traversal = await page.evaluate(async () => (await fetch('gigman://app/audio/%2e%2e%2flibrary.json')).status);
  assert.equal(traversal, 404);
  async function dragRegion(selector, deltaFraction) {
    const region = page.locator('.region').first(), target = selector ? region.locator(selector) : region;
    const box = await target.boundingBox(), wave = await region.locator('..').boundingBox();
    await page.mouse.move(box.x + box.width / 2, box.y + (selector ? box.height / 2 : box.height * 0.7));
    await page.mouse.down(); await page.mouse.move(box.x + box.width / 2 + wave.width * deltaFraction, box.y + (selector ? box.height / 2 : box.height * 0.7), { steps: 12 }); await page.mouse.up();
  }
  const regionStyle = () => page.locator('.region').first().evaluate(el => ({ left: parseFloat(el.style.left), width: parseFloat(el.style.width) }));
  const originalRegion = await regionStyle();
  await dragRegion(null, 0.12);
  let changedRegion = await regionStyle();
  assert.ok(Math.abs(changedRegion.left - originalRegion.left - 12) < 0.3, 'Mitte verschiebt die Sektion');
  assert.ok(Math.abs(changedRegion.width - originalRegion.width) < 0.01, 'Verschieben hält die Länge');
  await dragRegion('.handle-end', 0.07); changedRegion = await regionStyle();
  assert.ok(Math.abs(changedRegion.width - originalRegion.width - 7) < 0.3, 'Endgriff vergrößert die Sektion');
  const beforeStartResize = changedRegion;
  await dragRegion('.handle-start', 0.03); changedRegion = await regionStyle();
  assert.ok(Math.abs(changedRegion.width - beforeStartResize.width + 3) < 0.3, 'Startgriff verkleinert die Sektion');
  assert.ok(Math.abs(changedRegion.left - beforeStartResize.left - 3) < 0.3, 'Startgriff verändert den Start');
  await page.waitForTimeout(250);
  await page.locator('[data-action="youtube"]').click();
  await page.locator('[name="url"]').fill('https://example.com/video');
  await page.locator('dialog button[type="submit"]').click();
  await page.waitForFunction(() => document.querySelector('.form-error').textContent.includes('nur YouTube'));
  await page.locator('dialog [data-action="close-dialog"]').last().click();
  await page.evaluate(() => {
    window.liveLoopStarts = [];
    const start = AudioBufferSourceNode.prototype.start;
    AudioBufferSourceNode.prototype.start = function (...args) { window.liveLoopStarts.push({ offset: args[1], loop: this.loop, end: this.loopEnd }); return start.apply(this, args); };
  });
  await page.locator('#count').selectOption('0');
  await page.locator('.region').first().click(); await page.locator('[data-action="mode-loop"]').click();
  await page.locator('[data-action="play"]').click();
  await page.waitForFunction(() => window.liveLoopStarts.length === 1);
  await dragRegion(null, 0.02);
  await page.waitForFunction(() => window.liveLoopStarts.length === 2);
  const liveLoop = await page.evaluate(() => window.liveLoopStarts.at(-1));
  const bounds = (await page.locator('.region').first().getAttribute('title')).match(/· ([\d.]+)–([\d.]+) s/);
  assert.ok(liveLoop.loop && Math.abs(liveLoop.offset - Number(bounds[1])) < 0.01, 'Laufender Loop übernimmt verschobenen Start');
  assert.ok(Math.abs(liveLoop.end - Number(bounds[2])) < 0.01, 'Laufender Loop übernimmt verschobenes Ende');
  await page.keyboard.press('Escape'); await page.waitForTimeout(250);
  if (process.env.GIGMAN_TEST_YOUTUBE_LIVE) {
    await page.locator('[data-action="youtube"]').click();
    await page.locator('[name="url"]').fill(process.env.GIGMAN_TEST_YOUTUBE_LIVE);
    await page.locator('dialog button[type="submit"]').click();
    await page.waitForFunction(() => document.querySelectorAll('.song-row').length === 3 && !document.body.textContent.includes('Waveform wird geladen'), { timeout: 90000 });
    assert.ok((await page.locator('.song-title').last().innerText()).includes('Me at the zoo'));
    await page.locator('[data-action="preview"]').last().click();
    await page.waitForFunction(() => document.querySelector('#play-status').textContent.includes('Song anhören'));
    await page.keyboard.press('Escape');
    console.log('LIVE UI PASS: YouTube-URL → Fortschritt → MP3-Konvertierung → Song/Waveform in Setliste → Wiedergabe.');
  }
  await page.screenshot({ path: path.join(output, 'gigman-restored.png'), fullPage: true });
  await desktop.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1000, 720));
  await page.waitForFunction(() => window.innerWidth <= 1000);
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Kompakte Leiste passt auch bei minimaler Fensterbreite');
  await page.screenshot({ path: path.join(output, 'gigman-compact.png'), fullPage: true });
  await page.locator('[data-action="rename"]').click(); await page.locator('[name="name"]').fill('Sofort gespeichert'); await page.locator('dialog button[type="submit"]').click();
  await desktop.close(); desktop = null;
  const onClose = JSON.parse(await fs.readFile(path.join(data, 'library.json'), 'utf8'));
  assert.equal(onClose.setlists[0].name, 'Sofort gespeichert', 'Schließen wartet auf ausstehende Speicherung');
  console.log('PASS: MP3-Import, vollständige Vorschau, Waveform-Suche, Sektionen verschieben/vergrößern/verkleinern, Songfolge, Wechselpause, Audio-Tempo/Tonhöhe, Loop/Pause, Vorzählen, YouTube-URL-Validierung, Drag-and-drop, Neustart und Speicherung beim Schließen.');
} catch (error) {
  if (latestPage && !latestPage.isClosed()) {
    await latestPage.screenshot({ path: path.join(output, 'failure.png'), fullPage: true });
    console.log((await latestPage.locator('body').innerText()).slice(-4000));
    console.log('Renderer errors:', errors);
  }
  throw error;
} finally { if (desktop) await desktop.close(); }
